# Copyright 2021 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# TODO colluca: generate automatically with clustergen

---
address:
  # Snitch: cl_peripherals + 0x190
  barrier_reg:
    offset: 0x40000
    start: 0x120190
  cluster_base_hartid: 0x40000040
  cluster_id: 0x40000050
  cluster_num: 0x40000048
  nr_cores: 0x40000010
  # Snitch/Occamy: SOC_CTRL + 0x14
  # in Banshee also used as exit code location
  scratch_reg: 0x02000014
  uart: 0xF00B8000
  # Snitch: Bootdata.clint_base
  clint: 0xFFFF0000
  # Snitch: cl_peripherals + 0x180
  cl_clint: 0x10020180
  ## These parameters are not used, but Banshee requires them being defined
  tcdm_end: 0x00000000
  tcdm_start: 0x00000000
  # cluster_base_hartid: 0x00000000
  # cluster_id: 0x00000000
  # cluster_num: 0x00000000
  # nr_cores: 0x00000000
  wakeup_reg: 0x00000000
  ## End of unused parameters
architecture:
  num_cores: 9
  num_clusters: 1
  base_hartid: 0
bootrom:
  callbacks:
    - name: bootrom-cluster
      size: 0x34
  start: 0x01000000
  size: 0x20000 # end address of bootrom cluster 0x01020000
  offset: 0x0
  latency: 5
memory:
  dram:
    start: 0x80000000
    size: 0x70000000 # dram end address: 0xF0000000
    offset: 0x0 # dram is global for all clusters
    latency: 4
  periphs:
    start: 0x130000 # cluster "num_clusters" start address
    size: 0x10000   # size of the peripheral memory space
    offset: 0x40000 # offset to start address of next cluster
    latency: 2
    callbacks:
      - name: zero-memory
        size: 64000
  tcdm:
    start: 0x100000 # cluster "num_clusters" start address
    size: 0x020000   # size of the TCDM
    offset: 0x40000 # offset to next cluster is start + size + offset
    latency: 1
  ssr:
    num_dm: 3
